language: ruby
rvm:
  - 1.9.3
  - 2.0.0
before_script:
  - cp config/database.yml.development-sample config/database.yml
  - cp config/redis.yml.sample config/redis.yml
  - psql -c 'create database discourse_test;' -U postgres
  - rake db:migrate
  - export RUBY_GC_MALLOC_LIMIT=50000000
bundler_args: --without development
script: 'rake jshint && rake spec && bundle exec guard-jasmine --server-timeout=60'
services:
  - redis-server
