#redis://redistogo:611f8c35965c4409db1c52d29bcbded1@barreleye.redistogo.com:9531/
defaults: &defaults
  host: localhost
  port: 6379

development:
  host: localhost
  port: 6379
  db: 0
  cache_db: 2


test:
  <<: *defaults 
  db: 1

staging:
  <<: *defaults

production:
  host: barreleye.redistogo.com
  password: 611f8c35965c4409db1c52d29bcbded1
  port: 9531
  
